nameOverride: ""
fullnameOverride: ""

stone-scissors-paper-backend:
  replicaCount: 1

  image:
    repository: padigru/stone-scissors-paper-backend
    pullPolicy: IfNotPresent
    tag: ""

  imagePullSecrets: [ ]
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: { }

  podSecurityContext: { }

  securityContext: { }

  service:
    type: NodePort
    port: 80

  resources: { }

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80

  nodeSelector: { }

  tolerations: [ ]

  affinity: { }


stone-scissors-paper-frontend:
  replicaCount: 1

  image:
    repository: padigru/stone-scissors-paper-frontend
    pullPolicy: IfNotPresent
    tag: ""

  imagePullSecrets: [ ]
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: { }

  podSecurityContext: { }

  securityContext: { }

  service:
    type: NodePort
    port: 80

  resources: { }

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80

  nodeSelector: { }

  tolerations: [ ]

  affinity: { }
