replicaCount:

image:
  repository:
  pullPolicy:
  tag:

imagePullSecrets: []
nameOverride:
fullnameOverride:

podAnnotations:

podSecurityContext:

securityContext:

service:
  type:
  port:

resources:

autoscaling:
  enabled:
  minReplicas:
  maxReplicas:
  targetCPUUtilizationPercentage:

nodeSelector:

tolerations:

affinity:
