apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stone-scissors-paper-frontend.fullname" . }}-nginx-conf
  labels:
    {{- include "stone-scissors-paper-frontend.labels" . | nindent 4 }}
data:
  {{ (.Files.Glob "conf/default.conf").AsConfig | nindent 2 }}