apiVersion: v1
kind: Service
metadata:
  name: {{ include "stone-scissors-paper-frontend.fullname" . }}
  labels:
    {{- include "stone-scissors-paper-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30002
  selector:
    {{- include "stone-scissors-paper-frontend.selectorLabels" . | nindent 4 }}
